# ==========================================
# AI Digital Worker - File Automation Workflow
# ==========================================
# Skills: automation-workflows + ai-coding-assistant
# ==========================================

param(
    [string]$WatchFolder = "$env:USERPROFILE\Downloads",
    [string]$OutputFolder = "$env:USERPROFILE\Documents\AI_Workflow_Output",
    [switch]$Once
)

$ErrorActionPreference = "Continue"

function Write-Status { param($t) Write-Host "[INFO] $t" -ForegroundColor Cyan }
function Write-Success { param($t) Write-Host "[OK] $t" -ForegroundColor Green }
function Write-Warn { param($t) Write-Host "[WARN] $t" -ForegroundColor Yellow }

Write-Host ""
Write-Host "==========================================" -ForegroundColor Magenta
Write-Host "  AI Digital Worker - File Processor v1.0" -ForegroundColor Magenta
Write-Host "==========================================" -ForegroundColor Magenta
Write-Host ""

# Create output folder
if (-not (Test-Path $OutputFolder)) {
    New-Item -ItemType Directory -Path $OutputFolder -Force | Out-Null
    Write-Success "Created output folder: $OutputFolder"
}

# Scan files
Write-Status "Scanning: $WatchFolder"
$files = Get-ChildItem -Path $WatchFolder -File -ErrorAction SilentlyContinue | 
    Where-Object { $_.LastWriteTime -gt (Get-Date).AddDays(-7) } |
    Sort-Object LastWriteTime -Descending

if ($files.Count -eq 0) {
    Write-Warn "No recent files found"
    exit 0
}

Write-Success "Found $($files.Count) files"

# Categorize
$categories = @{
    Documents = @()
    Images = @()
    Code = @()
    Archives = @()
    Others = @()
}

foreach ($file in $files) {
    switch -Regex ($file.Extension) {
        '\.(txt|doc|docx|pdf|md)$' { $categories.Documents += $file }
        '\.(jpg|jpeg|png|gif|bmp|webp)$' { $categories.Images += $file }
        '\.(py|js|ps1|sh|bat|sql|html|css)$' { $categories.Code += $file }
        '\.(zip|rar|7z|tar|gz)$' { $categories.Archives += $file }
        Default { $categories.Others += $file }
    }
}

# Generate report
$reportTime = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$reportFile = Join-Path $OutputFolder "report_$(Get-Date -Format 'yyyyMMdd_HHmmss').md"

$docList = ($categories.Documents | ForEach-Object { "- $($_.Name)" }) -join "`n"
if (-not $docList) { $docList = "(none)" }

$imgList = ($categories.Images | ForEach-Object { "- $($_.Name)" }) -join "`n"
if (-not $imgList) { $imgList = "(none)" }

$codeList = ($categories.Code | ForEach-Object { "- $($_.Name)" }) -join "`n"
if (-not $codeList) { $codeList = "(none)" }

$report = @"
# AI Digital Worker Report

**Time:** $reportTime  
**Folder:** $WatchFolder  
**Output:** $OutputFolder  

## Stats

| Type | Count |
|------|-------|
| Documents | $($categories.Documents.Count) |
| Images | $($categories.Images.Count) |
| Code | $($categories.Code.Count) |
| Archives | $($categories.Archives.Count) |
| Others | $($categories.Others.Count) |
| **Total** | **$($files.Count)** |

## Files

### Documents
$docList

### Images
$imgList

### Code
$codeList

## Suggestions

$(if ($categories.Code.Count -gt 3) { "- Many code files - consider running code quality check" })
$(if ($categories.Documents.Count -gt 5) { "- Many documents - consider organizing" })
$(if ($categories.Images.Count -gt 10) { "- Many images - consider compression backup" })
$(if ($categories.Archives.Count -gt 0) { "- Found archives - consider extracting" })

---
*Generated by AI Digital Worker*
"@

$report | Out-File -FilePath $reportFile -Encoding UTF8
Write-Success "Report: $reportFile"

# Cleanup temp files
Write-Status "Cleaning temp files..."
$tempCleaned = 0
$tempFiles = Get-ChildItem -Path $WatchFolder -File -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -match 'tmp|temp|~$|\.crdownload|\.partial' }
foreach ($f in $tempFiles) {
    try {
        Remove-Item $f.FullName -Force -ErrorAction SilentlyContinue
        $tempCleaned++
    } catch {}
}
Write-Success "Cleaned $tempCleaned temp files"

# Calculate size
$totalSize = ($files | Measure-Object -Property Length -Sum).Sum
$totalSizeMB = [Math]::Round($totalSize / 1MB, 2)
Write-Success "Total size: $totalSizeMB MB"

# Summary
$summaryFile = Join-Path $OutputFolder "summary_$(Get-Date -Format 'yyyyMMdd').txt"
$summary = @"
AI Digital Worker Summary - $(Get-Date -Format 'yyyy-MM-dd')
==========================================
Folder: $WatchFolder
Files: $($files.Count)
Size: $totalSizeMB MB

By Type:
- Documents: $($categories.Documents.Count)
- Images: $($categories.Images.Count)
- Code: $($categories.Code.Count)
- Archives: $($categories.Archives.Count)
- Others: $($categories.Others.Count)
"@
$summary | Out-File -FilePath $summaryFile -Encoding UTF8
Write-Success "Summary: $summaryFile"

Write-Host ""
Write-Host "==========================================" -ForegroundColor Green
Write-Host "  DONE!" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Files: $($files.Count) | Temp Cleaned: $tempCleaned | Size: $totalSizeMB MB" -ForegroundColor Cyan
Write-Host ""

# Open output folder
Start-Process explorer.exe $OutputFolder
